# Introduction

## Foreword

I thought It would be fun to create a book covering the things that I have learnt this past year and a half while creating a (hopefully) useful tool for future students. I also really enjoy opensource projects such as R and really think that it is a brilliant workspace. It is not only flexible but creates a very structured environment where all your decisions throughout the analysis is easily documented and shared. In short, I like R and RStudio. The problem is that R is hard, the learning curve is slow, and if you are a psychologist, the opportunities to learn programming are sparse unless you seek them out for yourself. With this book I hope to create an accessible guide to how you can use R for your studies and hopefully your future work. Now is a good time to point out that I am not a statistician, as of writing this I have not even graduated from the master´s program. Thus, this book should not be treated as an authoritative voice on how you should do statistics or interpret your results. The aim here is simple, it is to guide you through some of the statistical analyses that you will encounter and introduce the R programming language in the meantime. There will of course be some explanations of the tools that we use in terms of their statistical properties and interpretations of the results from our analyses, but I cannot stress enough that this is not a book about statistics, it´s a book about doing statistics in R. It´s designed to be brief and easily skimmed though in the sense that you won’t have to read so much of my blathering to understand the interesting bits - the code. 

The general layout of the applied chapters will be analyses of the working examples in Discovering statistics by Andy Field (when applicable) and some workshop exercises. I will also end each applied chapter by finding some real data from an article and working through their analysis.  

In sum, this is a compilation of the topics covered in the master´s programme in psychological science at the university of Gothenburg in 2021/22 with some additional chapters by yours truly on some of the things that I think are useful and important. It is a supplementary text that simply translates the analyses described in the literature into R-code. It is for students who want to learn R but don’t know where to start. It can be hard to learn things on your own without any real incentives, and I hope that this book can coax some people into R through it´s accessibility and relevance to what you will be doing in class anyways. Good luck and happy reading/coding.

P.s, If you are a statistician, stop reading here, only pain will follow. 

## The grain of salt

If it wasn’t painfully clear from the foreword, I do not presume myself to have any sort of authority in matters of statistics (or software for that matter). This text is as much for my own education as for anyone who wishes to use it as a guide. With that said, there are some disclaimers needed. In general, I prefer Bayesian solutions to data analytic problems compared to frequentist solutions. Since I will mostly cover non-Bayesian analyses, this clarification has value, since much of what we will be doing in this “book” is not my preferred way of doing statistics. This does not mean that the modelling that we will be doing is “wrong” or misleading, I’m certainly not a Bayesian fundamentalist, but I generally prefer full posterior estimations and bayes factors to p-values and confidence intervals. I cannot stress enough that this is preference, there are many cases where frequent and Bayesian statistics come to similar conclusions, but in some cases, Bayes can help you. And if Bayes does not help you, then what is the reason for doing it? I would again like to stress that I am neither a psychologist, statistician, compute scientists or a teacher, so I am very much out of my depth here, but if I were to pretend that I were any of those things there would be three things that I would like to say before you start going through this “book”: 
1: Be aware of survival bias. All of the code/models (online or in this book) are victims of survival bias. Before those successful models or codes were written, there was numerus unsuccessful attempts to specify that model or code. So, when your model does not work or your code returns am error, be aware that it is a part of the process. And remember, all the successful things you see rests atop a pile of discarded alternatives! 
2: Horses for courses. This old adage is very much applied to statistics. Individuals have different preferences in how they wish to solve certain problems. Annoyingly, there are often many ways to solve similar problems, but it is important to remember to use the right horse for the course. This is not meant to be interpreted in a cook-book kind of way but rather that certain analytical solutions are suited for different things. So remember what YOUR question is and try to find the right analytical tool for that specific problem. 
3: Embrace uncertainty. It is quite rare, in my experience, that scientists talk about what they do not know, or report statistics in a way that emphasises their uncertainty about a topic. Don´t think that you need to have an answer to everything, it is very hard to “know” anything – that’s why science is hard. This does not mean that you should be afraid to make predictions, but it does mean that you should be very open to being wrong and to be conservative with what you are certain about. 

Hopefully this section can cover my back to the people who might take extreme issue with me writing this little guide and to give the readers of this a little bit of insight in how I reason about science. 

## Some useful resources 

In this section I wish to direct you to some of great resources that exists on R-programming and statistics in general. Note that not all of these are free, but some of them are. Firstly I must recommend Hadley Wickhams book “R for data science”. It gives a wonderful introduction to how you can use some of the most convenient R functions. It is an essential of R programming and can be found here: https://r4ds.had.co.nz/. 
In terms of statistics, I have a few books that I have thoroughly enjoyed. My favourite is “statistical rethinking” by Richard McElreath. It is splendid book on Bayesian inference using R and STAN (a language for Bayesian modelling and sampling). In 2022 lectures by McElreath was published to youtube giving the book even more accessibility than it already had. Another book (again on Bayesian inference) is “doing Bayesian data analysis” by John Kruschke. While I prefere McElreath´s book this is a very nice introduction to statistics and Bayesian inference. A book which only makes subtle Bayesian hints is “regression and other stories” by Gelman, Hill and Vehtari. This is a good book for getting into regression analysis – which is probably a good thing to get in to as a scientist. Another book on statistics that has been of great use to me is “Understanding the New Statistics” by Geoff Cumming. This is not a book on Bayesian statistics but covers some of the important aspects of statistics in the social sciences. Note that I have not mentioned “discovering statistics” by Andy Field, this is not because that I dislike that book (I don’t), but if I had recommendations I needed to make, I wouldn’t include that particular book – in comparison to it´s competitors it does not cut it. However, it admittedly has pedagogical value, thus, we will use much of the data files from Field. This is not because I have any unrequited love for Field, but because the book will probably be familiar to you (the reader) and covered in the courses in the programme. There are of course many other books that are great but that I will not link here, I say, whichever book that makes you do good statistics is a good book for you (but if you want  inspiration feel free to check out the links below). 

Links: 
McElreath: https://github.com/rmcelreath/stat_rethinking_2022 
Kruschke: https://www.sciencedirect.com/book/9780124058880/doing-bayesian-data-analysis 
Gelman, Hill and Vehtari: https://avehtari.github.io/ROS-Examples/ 
Cumming: https://thenewstatistics.com/itns/ 


